version: '3'
services:
  meinedb:
    image: postgres:latest
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test123
  playerdbweb:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "meinedb"