name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: bitnami/java:11.0.13-prod

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t jetty-img .:$(date +%s)
